dist: xenial

language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - nightly
  - pypy3.5-6.0
matrix:
  allow_failures:
    - python: nightly
install:
  - pip install -q -r test-requirements.txt --no-cache-dir --upgrade
script:
  - pytest tests
after_success: codecov
