sudo: false

language: python

python:
  - 3.5
  - 3.6
  - nightly
  - pypy3.5
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
env:
  - APISPEC_VERSION=0.38.0
  - APISPEC_VERSION=0.39.0
install:
  - pip install -q -r dev-requirements.txt
  - pip install -q apispec==$APISPEC_VERSION
script:
  - pytest tests
after_success: codecov
