dist: xenial

language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - nightly
  - pypy3.5-6.0
env:
  - APISPEC_VERSION=0.38.0
  - APISPEC_VERSION=0.39.0
matrix:
  allow_failures:
    - python: nightly
install:
  - pip install -q -r dev-requirements.txt --no-cache-dir --upgrade
  - pip install -q apispec==$APISPEC_VERSION
script:
  - pytest tests
after_success: codecov
